### Evolution Parameters ###
random_num_seed = 1
population_size = 500           # TODO confirm with Emily/Charles
num_generations = 1000          # TODO confirm with Emily/Charles
per_site_mut_rate = 0.3
mut_effect_size = 0.1
selection_scheme = "NSGAII"
percent_no_ridge_at_start = 0.1  # the % of indiv generated w/ no ridge when
                                 # generating a new starting population

### Individual Parameters ###

# Horn Parameters
NUM_WALL_PAIRS = 2

MIN_FLARE_LENGTH = 2.0   # TODO confirm this with horn guys
MAX_FLARE_LENGTH = 5.0   # TODO confirm this with horn guys

MIN_WAVEGUIDE_HEIGHT = 200.0
MAX_WAVEGUIDE_HEIGHT = 1000.0

MIN_WAVEGUIDE_LENGTH = 100.0
MAX_WAVEGUIDE_LENGTH = 1000.0

MIN_WAVEGUIDE_WIDTH = 100.0   # TODO confirm this with horn guys
MAX_WAVEGUIDE_WIDTH = 1000.0  # TODO confirm this with horn guys

# WallPair Parameters
MIN_ANGLE = 0.0              # degrees; exclusive
MAX_ANGLE = 90.0             # degrees; inclusive

MIN_RIDGE_HEIGHT = 0.0       # % of horn; exclusive
MAX_RIDGE_HEIGHT = 100.0     # % of horn; inclusive

MIN_RIDGE_WIDTH_TOP = 0.0    # % of wall width at top of horn; inclusive
MAX_RIDGE_WIDTH_TOP = 100.0  # %; inclusive

MIN_RIDGE_WIDTH_BOTTOM = 0.0     # %; inclusive
MAX_RIDGE_WIDTH_BOTTOM = 100.0   # %; inclusive

MIN_RIDGE_THICKNESS_TOP = 0.0    # % of distance to the middle of the horn;
# inclusive
MAX_RIDGE_THICKNESS_TOP = 100.0  # %; inclusive

MIN_RIDGE_THICKNESS_BOTTOM = 0.0    # %; % of distance to the middle of the
# horn; inclusive
MAX_RIDGE_THICKNESS_BOTTOM = 100.0  # %; inclusive
