name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # --ignore-requires-python ensures docs deps don't break install on early python versions
        sudo apt-get install liboctomap-dev
        sudo apt-get install libfcl-dev
        if [ -f requirements.txt ]; then pip install --ignore-requires-python -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python -m pytest