name: Lint

on:
  push:
    paths:
      - 'src/**.py'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff
      run: ruff check src/